# Generated by Django 5.0.7 on 2025-08-04 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecareapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor')], default='patient', max_length=10),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='dashboard_patient/'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='doctors/'),
        ),
    ]
