# Generated by Django 5.0.7 on 2025-08-27 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifecareapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='slot_duration',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='start_time',
        ),
    ]
