# Generated by Django 5.0.6 on 2025-04-23 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifecareapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
