# Generated by Django 5.0.6 on 2025-03-31 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifecareapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
