# Generated by Django 5.0.7 on 2025-04-26 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifecareapp', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photos',
            new_name='photo',
        ),
    ]
