# Generated by Django 5.0.7 on 2025-09-02 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecareapp', '0002_alter_booking_options_alter_booking_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='lifecareapp.booking'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='lifecareapp.patientprofile'),
        ),
    ]
