# Generated by Django 5.0.7 on 2025-08-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecareapp', '0002_doctorprofile_end_time_doctorprofile_slot_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='slot_duration',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='start_time',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='available_time_slots',
            field=models.JSONField(blank=True, default=list, help_text="List of available time slots in 'HH:MM AM/PM' format"),
        ),
    ]
