# Generated by Django 5.0.7 on 2025-08-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecareapp', '0002_remove_doctorprofile_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='slot_duration',
            field=models.IntegerField(default=30, help_text='Duration in minutes'),
        ),
    ]
