# Generated by Django 5.0.6 on 2025-09-17 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifecareapp', '0003_alter_booking_patient'),
        ('lifecareapp', '0003_payment_booking_alter_booking_patient'),
    ]

    operations = [
    ]
