# Generated by Django 5.0.7 on 2025-08-21 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecareapp', '0003_remove_doctorprofile_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctoravailability',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='lifecareapp.doctorprofile'),
        ),
    ]
