# Generated by Django 5.0.6 on 2025-09-17 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecareapp', '0004_merge_20250917_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_admin_approval', 'Pending Admin Approval'), ('approved_admin', 'Approved by Admin'), ('delivered', 'Delivered to Patient'), ('paid', 'Paid')], default='pending_admin_approval', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='lifecareapp.equipment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_requests', to='lifecareapp.patientprofile')),
            ],
        ),
    ]
