# Generated by Django 5.0.7 on 2025-08-21 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecareapp', '0004_alter_doctoravailability_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='doctoravailability',
            options={'ordering': ('date', 'start_time')},
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='available_time_slots',
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.CharField(blank=True, help_text='Appointment time (HH:MM format)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='end_time',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='slot_duration',
            field=models.IntegerField(default=30, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='start_time',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='lifecareapp.doctorprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('doctor', 'date', 'time')},
        ),
    ]
