# Generated by Django 5.0.7 on 2025-05-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecareapp', '0004_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='medical_history_pdf',
            field=models.FileField(blank=True, null=True, upload_to='patient_medical_history/'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='medical_history_uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
