# Generated by Django 5.0.7 on 2025-06-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecareapp', '0006_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='appointment_type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('checkup', 'General Checkup'), ('follow_up', 'Follow-up'), ('emergency', 'Emergency'), ('specialist', 'Specialist Visit'), ('lab_test', 'Laboratory Test'), ('vaccination', 'Vaccination'), ('physical_therapy', 'Physical Therapy')], default='consultation', help_text='Type of appointment', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost of appointment in KES', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(blank=True, help_text='Appointment date', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='queue_position',
            field=models.PositiveIntegerField(blank=True, help_text='Position in queue for the appointment', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
